export interface Club {
  id: string;
  name: string;
  shortName: string;
  abbreviation: string;
  league: string;
  gradientStart: string;
  gradientEnd: string;
  accentColor: string;
  badgeBackground: string;
}

export const CLUBS: Club[] = [
  // ── Premier League ──────────────────────────────────────────────
  {
    id: "man-city",
    name: "Manchester City",
    shortName: "Man City",
    abbreviation: "MCFC",
    league: "Premier League",
    gradientStart: "#6CADDF",
    gradientEnd: "#1C2C5B",
    accentColor: "#6CADDF",
    badgeBackground: "#1C2C5B",
  },
  {
    id: "arsenal",
    name: "Arsenal",
    shortName: "Arsenal",
    abbreviation: "AFC",
    league: "Premier League",
    gradientStart: "#9C0000",
    gradientEnd: "#EF0107",
    accentColor: "#EF0107",
    badgeBackground: "#EF0107",
  },
  {
    id: "chelsea",
    name: "Chelsea",
    shortName: "Chelsea",
    abbreviation: "CFC",
    league: "Premier League",
    gradientStart: "#034694",
    gradientEnd: "#003CBF",
    accentColor: "#034694",
    badgeBackground: "#034694",
  },
  {
    id: "liverpool",
    name: "Liverpool",
    shortName: "Liverpool",
    abbreviation: "LFC",
    league: "Premier League",
    gradientStart: "#C8102E",
    gradientEnd: "#8B0000",
    accentColor: "#C8102E",
    badgeBackground: "#C8102E",
  },
  {
    id: "man-utd",
    name: "Manchester United",
    shortName: "Man United",
    abbreviation: "MUFC",
    league: "Premier League",
    gradientStart: "#DA291C",
    gradientEnd: "#8C0000",
    accentColor: "#DA291C",
    badgeBackground: "#DA291C",
  },
  {
    id: "tottenham",
    name: "Tottenham Hotspur",
    shortName: "Spurs",
    abbreviation: "THFC",
    league: "Premier League",
    gradientStart: "#132257",
    gradientEnd: "#0A1540",
    accentColor: "#FFFFFF",
    badgeBackground: "#132257",
  },

  // ── La Liga ─────────────────────────────────────────────────────
  {
    id: "barcelona",
    name: "FC Barcelona",
    shortName: "Barcelona",
    abbreviation: "FCB",
    league: "La Liga",
    gradientStart: "#004D98",
    gradientEnd: "#A50044",
    accentColor: "#EDBB00",
    badgeBackground: "#004D98",
  },
  {
    id: "real-madrid",
    name: "Real Madrid",
    shortName: "Real Madrid",
    abbreviation: "RMA",
    league: "La Liga",
    gradientStart: "#00529F",
    gradientEnd: "#003070",
    accentColor: "#FEBE10",
    badgeBackground: "#00529F",
  },

  // ── Ligue 1 ─────────────────────────────────────────────────────
  {
    id: "psg",
    name: "Paris Saint-Germain",
    shortName: "PSG",
    abbreviation: "PSG",
    league: "Ligue 1",
    gradientStart: "#003370",
    gradientEnd: "#001B40",
    accentColor: "#EE1F39",
    badgeBackground: "#003370",
  },

  // ── Serie A ─────────────────────────────────────────────────────
  {
    id: "juventus",
    name: "Juventus",
    shortName: "Juventus",
    abbreviation: "JFC",
    league: "Serie A",
    gradientStart: "#1A1A1A",
    gradientEnd: "#000000",
    accentColor: "#FFFFFF",
    badgeBackground: "#1A1A1A",
  },

  // ── Bundesliga ──────────────────────────────────────────────────
  {
    id: "dortmund",
    name: "Borussia Dortmund",
    shortName: "Dortmund",
    abbreviation: "BVB",
    league: "Bundesliga",
    gradientStart: "#FDE100",
    gradientEnd: "#D4B800",
    accentColor: "#000000",
    badgeBackground: "#FDE100",
  },
  {
    id: "bayern",
    name: "Bayern Munich",
    shortName: "Bayern",
    abbreviation: "FCB",
    league: "Bundesliga",
    gradientStart: "#DC052D",
    gradientEnd: "#8B001B",
    accentColor: "#DC052D",
    badgeBackground: "#DC052D",
  },

  // ── NFL ─────────────────────────────────────────────────────────
  {
    id: "ny-giants",
    name: "New York Giants",
    shortName: "Giants",
    abbreviation: "NYG",
    league: "NFL",
    gradientStart: "#0B2265",
    gradientEnd: "#050E30",
    accentColor: "#A71930",
    badgeBackground: "#0B2265",
  },
  {
    id: "la-rams",
    name: "Los Angeles Rams",
    shortName: "Rams",
    abbreviation: "LAR",
    league: "NFL",
    gradientStart: "#003594",
    gradientEnd: "#001A50",
    accentColor: "#FFA300",
    badgeBackground: "#003594",
  },
  {
    id: "bal-ravens",
    name: "Baltimore Ravens",
    shortName: "Ravens",
    abbreviation: "BAL",
    league: "NFL",
    gradientStart: "#241773",
    gradientEnd: "#100A33",
    accentColor: "#9E7C0C",
    badgeBackground: "#241773",
  },
  {
    id: "den-broncos",
    name: "Denver Broncos",
    shortName: "Broncos",
    abbreviation: "DEN",
    league: "NFL",
    gradientStart: "#FB4F14",
    gradientEnd: "#B83000",
    accentColor: "#002244",
    badgeBackground: "#FB4F14",
  },
  {
    id: "lv-raiders",
    name: "Las Vegas Raiders",
    shortName: "Raiders",
    abbreviation: "LVR",
    league: "NFL",
    gradientStart: "#000000",
    gradientEnd: "#1A1A1A",
    accentColor: "#A5ACAF",
    badgeBackground: "#000000",
  },
  {
    id: "min-vikings",
    name: "Minnesota Vikings",
    shortName: "Vikings",
    abbreviation: "MIN",
    league: "NFL",
    gradientStart: "#4F2683",
    gradientEnd: "#2A1244",
    accentColor: "#FFC62F",
    badgeBackground: "#4F2683",
  },
  {
    id: "tb-bucs",
    name: "Tampa Bay Buccaneers",
    shortName: "Buccaneers",
    abbreviation: "TB",
    league: "NFL",
    gradientStart: "#D50A0A",
    gradientEnd: "#8B0000",
    accentColor: "#FF7900",
    badgeBackground: "#D50A0A",
  },
  {
    id: "ari-cardinals",
    name: "Arizona Cardinals",
    shortName: "Cardinals",
    abbreviation: "ARI",
    league: "NFL",
    gradientStart: "#97233F",
    gradientEnd: "#5A0F20",
    accentColor: "#FFB612",
    badgeBackground: "#97233F",
  },
  {
    id: "atl-falcons",
    name: "Atlanta Falcons",
    shortName: "Falcons",
    abbreviation: "ATL",
    league: "NFL",
    gradientStart: "#A71930",
    gradientEnd: "#6B0F1E",
    accentColor: "#A5ACAF",
    badgeBackground: "#A71930",
  },
  {
    id: "kc-chiefs",
    name: "Kansas City Chiefs",
    shortName: "Chiefs",
    abbreviation: "KC",
    league: "NFL",
    gradientStart: "#E31837",
    gradientEnd: "#8B0000",
    accentColor: "#FFB612",
    badgeBackground: "#E31837",
  },
  {
    id: "dal-cowboys",
    name: "Dallas Cowboys",
    shortName: "Cowboys",
    abbreviation: "DAL",
    league: "NFL",
    gradientStart: "#003594",
    gradientEnd: "#001A5E",
    accentColor: "#869397",
    badgeBackground: "#003594",
  },
  {
    id: "gb-packers",
    name: "Green Bay Packers",
    shortName: "Packers",
    abbreviation: "GB",
    league: "NFL",
    gradientStart: "#203731",
    gradientEnd: "#0D1F1A",
    accentColor: "#FFB612",
    badgeBackground: "#203731",
  },
  {
    id: "ne-patriots",
    name: "New England Patriots",
    shortName: "Patriots",
    abbreviation: "NE",
    league: "NFL",
    gradientStart: "#002244",
    gradientEnd: "#000E20",
    accentColor: "#C60C30",
    badgeBackground: "#002244",
  },
  {
    id: "sf-49ers",
    name: "San Francisco 49ers",
    shortName: "49ers",
    abbreviation: "SF",
    league: "NFL",
    gradientStart: "#AA0000",
    gradientEnd: "#7A0000",
    accentColor: "#B3995D",
    badgeBackground: "#AA0000",
  },
  {
    id: "chi-bears",
    name: "Chicago Bears",
    shortName: "Bears",
    abbreviation: "CHI",
    league: "NFL",
    gradientStart: "#0B162A",
    gradientEnd: "#040A14",
    accentColor: "#C83803",
    badgeBackground: "#0B162A",
  },
  {
    id: "pit-steelers",
    name: "Pittsburgh Steelers",
    shortName: "Steelers",
    abbreviation: "PIT",
    league: "NFL",
    gradientStart: "#101820",
    gradientEnd: "#000000",
    accentColor: "#FFB612",
    badgeBackground: "#101820",
  },
  {
    id: "sea-seahawks",
    name: "Seattle Seahawks",
    shortName: "Seahawks",
    abbreviation: "SEA",
    league: "NFL",
    gradientStart: "#002244",
    gradientEnd: "#000E20",
    accentColor: "#69BE28",
    badgeBackground: "#002244",
  },
  {
    id: "phi-eagles",
    name: "Philadelphia Eagles",
    shortName: "Eagles",
    abbreviation: "PHI",
    league: "NFL",
    gradientStart: "#004C54",
    gradientEnd: "#002A30",
    accentColor: "#A5ACAF",
    badgeBackground: "#004C54",
  },
  {
    id: "buf-bills",
    name: "Buffalo Bills",
    shortName: "Bills",
    abbreviation: "BUF",
    league: "NFL",
    gradientStart: "#00338D",
    gradientEnd: "#001850",
    accentColor: "#C60C30",
    badgeBackground: "#00338D",
  },
  {
    id: "mia-dolphins",
    name: "Miami Dolphins",
    shortName: "Dolphins",
    abbreviation: "MIA",
    league: "NFL",
    gradientStart: "#008E97",
    gradientEnd: "#005F66",
    accentColor: "#FC4C02",
    badgeBackground: "#008E97",
  },

  // ── NBA ─────────────────────────────────────────────────────────
  {
    id: "la-lakers",
    name: "Los Angeles Lakers",
    shortName: "Lakers",
    abbreviation: "LAL",
    league: "NBA",
    gradientStart: "#552583",
    gradientEnd: "#2D1048",
    accentColor: "#FDB927",
    badgeBackground: "#552583",
  },
  {
    id: "gs-warriors",
    name: "Golden State Warriors",
    shortName: "Warriors",
    abbreviation: "GSW",
    league: "NBA",
    gradientStart: "#1D428A",
    gradientEnd: "#0D1F44",
    accentColor: "#FFC72C",
    badgeBackground: "#1D428A",
  },
  {
    id: "chi-bulls",
    name: "Chicago Bulls",
    shortName: "Bulls",
    abbreviation: "CHI",
    league: "NBA",
    gradientStart: "#CE1141",
    gradientEnd: "#8B0020",
    accentColor: "#CE1141",
    badgeBackground: "#CE1141",
  },
  {
    id: "bos-celtics",
    name: "Boston Celtics",
    shortName: "Celtics",
    abbreviation: "BOS",
    league: "NBA",
    gradientStart: "#007A33",
    gradientEnd: "#004D20",
    accentColor: "#BA9653",
    badgeBackground: "#007A33",
  },
  {
    id: "mia-heat",
    name: "Miami Heat",
    shortName: "Heat",
    abbreviation: "MIA",
    league: "NBA",
    gradientStart: "#98002E",
    gradientEnd: "#5C001C",
    accentColor: "#F9A01B",
    badgeBackground: "#98002E",
  },
  {
    id: "ny-knicks",
    name: "New York Knicks",
    shortName: "Knicks",
    abbreviation: "NYK",
    league: "NBA",
    gradientStart: "#006BB6",
    gradientEnd: "#004070",
    accentColor: "#F58426",
    badgeBackground: "#006BB6",
  },
  {
    id: "phx-suns",
    name: "Phoenix Suns",
    shortName: "Suns",
    abbreviation: "PHX",
    league: "NBA",
    gradientStart: "#1D1160",
    gradientEnd: "#0D0830",
    accentColor: "#E56020",
    badgeBackground: "#1D1160",
  },
  {
    id: "mil-bucks",
    name: "Milwaukee Bucks",
    shortName: "Bucks",
    abbreviation: "MIL",
    league: "NBA",
    gradientStart: "#00471B",
    gradientEnd: "#002810",
    accentColor: "#EEE1C6",
    badgeBackground: "#00471B",
  },

  // ── MLB ─────────────────────────────────────────────────────────
  {
    id: "stl-cardinals",
    name: "St. Louis Cardinals",
    shortName: "Cardinals",
    abbreviation: "STL",
    league: "MLB",
    gradientStart: "#C41E3A",
    gradientEnd: "#0C2340",
    accentColor: "#FEDB00",
    badgeBackground: "#0C2340",
  },
  {
    id: "ny-yankees",
    name: "New York Yankees",
    shortName: "Yankees",
    abbreviation: "NYY",
    league: "MLB",
    gradientStart: "#003087",
    gradientEnd: "#001550",
    accentColor: "#C4CED4",
    badgeBackground: "#003087",
  },
  {
    id: "la-dodgers",
    name: "Los Angeles Dodgers",
    shortName: "Dodgers",
    abbreviation: "LAD",
    league: "MLB",
    gradientStart: "#005A9C",
    gradientEnd: "#003060",
    accentColor: "#EF3E42",
    badgeBackground: "#005A9C",
  },
  {
    id: "bos-redsox",
    name: "Boston Red Sox",
    shortName: "Red Sox",
    abbreviation: "BOS",
    league: "MLB",
    gradientStart: "#BD3039",
    gradientEnd: "#0C2340",
    accentColor: "#BD3039",
    badgeBackground: "#0C2340",
  },
  {
    id: "chi-cubs",
    name: "Chicago Cubs",
    shortName: "Cubs",
    abbreviation: "CHC",
    league: "MLB",
    gradientStart: "#0E3386",
    gradientEnd: "#071E50",
    accentColor: "#CC3433",
    badgeBackground: "#0E3386",
  },
  {
    id: "hou-astros",
    name: "Houston Astros",
    shortName: "Astros",
    abbreviation: "HOU",
    league: "MLB",
    gradientStart: "#002D62",
    gradientEnd: "#001230",
    accentColor: "#EB6E1F",
    badgeBackground: "#002D62",
  },

  // ── NHL ─────────────────────────────────────────────────────────
  {
    id: "pit-penguins",
    name: "Pittsburgh Penguins",
    shortName: "Penguins",
    abbreviation: "PIT",
    league: "NHL",
    gradientStart: "#000000",
    gradientEnd: "#1A1A1A",
    accentColor: "#FCB514",
    badgeBackground: "#000000",
  },
  {
    id: "chi-hawks",
    name: "Chicago Blackhawks",
    shortName: "Blackhawks",
    abbreviation: "CHI",
    league: "NHL",
    gradientStart: "#CF0A2C",
    gradientEnd: "#8B0018",
    accentColor: "#FF6720",
    badgeBackground: "#CF0A2C",
  },
  {
    id: "tor-leafs",
    name: "Toronto Maple Leafs",
    shortName: "Maple Leafs",
    abbreviation: "TOR",
    league: "NHL",
    gradientStart: "#00205B",
    gradientEnd: "#000E30",
    accentColor: "#00205B",
    badgeBackground: "#00205B",
  },
  {
    id: "bos-bruins",
    name: "Boston Bruins",
    shortName: "Bruins",
    abbreviation: "BOS",
    league: "NHL",
    gradientStart: "#111111",
    gradientEnd: "#000000",
    accentColor: "#FCB514",
    badgeBackground: "#111111",
  },
  {
    id: "vgk-knights",
    name: "Vegas Golden Knights",
    shortName: "Golden Knights",
    abbreviation: "VGK",
    league: "NHL",
    gradientStart: "#333F42",
    gradientEnd: "#1A2124",
    accentColor: "#B4975A",
    badgeBackground: "#333F42",
  },
  {
    id: "ny-rangers",
    name: "New York Rangers",
    shortName: "Rangers",
    abbreviation: "NYR",
    league: "NHL",
    gradientStart: "#0038A8",
    gradientEnd: "#001E60",
    accentColor: "#CE1126",
    badgeBackground: "#0038A8",
  },
  {
    id: "col-avs",
    name: "Colorado Avalanche",
    shortName: "Avalanche",
    abbreviation: "COL",
    league: "NHL",
    gradientStart: "#6F263D",
    gradientEnd: "#3D1020",
    accentColor: "#236192",
    badgeBackground: "#6F263D",
  },
  {
    id: "tb-lightning",
    name: "Tampa Bay Lightning",
    shortName: "Lightning",
    abbreviation: "TBL",
    league: "NHL",
    gradientStart: "#002868",
    gradientEnd: "#001030",
    accentColor: "#FFFFFF",
    badgeBackground: "#002868",
  },

  // ── MLS ─────────────────────────────────────────────────────────
  {
    id: "la-galaxy",
    name: "LA Galaxy",
    shortName: "LA Galaxy",
    abbreviation: "LAG",
    league: "MLS",
    gradientStart: "#00245D",
    gradientEnd: "#000E28",
    accentColor: "#FFD700",
    badgeBackground: "#00245D",
  },
  {
    id: "atl-united",
    name: "Atlanta United FC",
    shortName: "Atlanta United",
    abbreviation: "ATL",
    league: "MLS",
    gradientStart: "#80000A",
    gradientEnd: "#400005",
    accentColor: "#9C8B1E",
    badgeBackground: "#80000A",
  },
  {
    id: "sea-sounders",
    name: "Seattle Sounders FC",
    shortName: "Sounders",
    abbreviation: "SEA",
    league: "MLS",
    gradientStart: "#5D9741",
    gradientEnd: "#3A5E28",
    accentColor: "#4B2E83",
    badgeBackground: "#5D9741",
  },
  {
    id: "int-miami",
    name: "Inter Miami CF",
    shortName: "Inter Miami",
    abbreviation: "MIA",
    league: "MLS",
    gradientStart: "#231F20",
    gradientEnd: "#100E0F",
    accentColor: "#F7B5CD",
    badgeBackground: "#231F20",
  },
  {
    id: "por-timbers",
    name: "Portland Timbers",
    shortName: "Timbers",
    abbreviation: "POR",
    league: "MLS",
    gradientStart: "#004812",
    gradientEnd: "#002508",
    accentColor: "#EBD93A",
    badgeBackground: "#004812",
  },
  {
    id: "nyc-fc",
    name: "New York City FC",
    shortName: "NYCFC",
    abbreviation: "NYC",
    league: "MLS",
    gradientStart: "#003087",
    gradientEnd: "#001550",
    accentColor: "#6CACE4",
    badgeBackground: "#003087",
  },
  {
    id: "tor-fc",
    name: "Toronto FC",
    shortName: "Toronto FC",
    abbreviation: "TFC",
    league: "MLS",
    gradientStart: "#B81137",
    gradientEnd: "#700020",
    accentColor: "#B81137",
    badgeBackground: "#B81137",
  },
];

export const DEFAULT_CLUB_ID = "man-city";

export function getClubById(id: string): Club {
  return CLUBS.find((c) => c.id === id) ?? CLUBS[0];
}

export const SOCCER_LEAGUES = ["Premier League", "La Liga", "Ligue 1", "Serie A", "Bundesliga"];

// ESPN CDN logo URLs — used in the onboarding club picker
const nfl = (code: string) => `https://a.espncdn.com/i/teamlogos/nfl/500/${code}.png`;
const nba = (code: string) => `https://a.espncdn.com/i/teamlogos/nba/500/${code}.png`;
const mlb = (code: string) => `https://a.espncdn.com/i/teamlogos/mlb/500/${code}.png`;
const nhl = (code: string) => `https://a.espncdn.com/i/teamlogos/nhl/500/${code}.png`;
const soccer = (id: number) => `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`;

export const CLUB_LOGO_URLS: Record<string, string> = {
  // NFL
  "ny-giants":    nfl("nyg"),
  "la-rams":      nfl("lar"),
  "bal-ravens":   nfl("bal"),
  "den-broncos":  nfl("den"),
  "lv-raiders":   nfl("lv"),
  "min-vikings":  nfl("min"),
  "tb-bucs":      nfl("tb"),
  "ari-cardinals": nfl("ari"),
  "atl-falcons":  nfl("atl"),
  "kc-chiefs":    nfl("kc"),
  "dal-cowboys":  nfl("dal"),
  "gb-packers":   nfl("gb"),
  "ne-patriots":  nfl("ne"),
  "sf-49ers":     nfl("sf"),
  "chi-bears":    nfl("chi"),
  "pit-steelers": nfl("pit"),
  "sea-seahawks": nfl("sea"),
  "phi-eagles":   nfl("phi"),
  "buf-bills":    nfl("buf"),
  "mia-dolphins": nfl("mia"),
  // NBA
  "la-lakers":    nba("lal"),
  "gs-warriors":  nba("gs"),
  "chi-bulls":    nba("chi"),
  "bos-celtics":  nba("bos"),
  "mia-heat":     nba("mia"),
  "ny-knicks":    nba("ny"),
  "phx-suns":     nba("phx"),
  "mil-bucks":    nba("mil"),
  // MLB
  "stl-cardinals": mlb("stl"),
  "ny-yankees":   mlb("nyy"),
  "la-dodgers":   mlb("lad"),
  "bos-redsox":   mlb("bos"),
  "chi-cubs":     mlb("chc"),
  "hou-astros":   mlb("hou"),
  // NHL
  "pit-penguins": nhl("pit"),
  "chi-hawks":    nhl("chi"),
  "tor-leafs":    nhl("tor"),
  "bos-bruins":   nhl("bos"),
  "vgk-knights":  nhl("vgk"),
  "ny-rangers":   nhl("nyr"),
  "col-avs":      nhl("col"),
  "tb-lightning": nhl("tb"),
  // MLS
  "la-galaxy":    soccer(392),
  "atl-united":   soccer(20116),
  "sea-sounders": soccer(9726),
  "int-miami":    soccer(28151),
  "por-timbers":  soccer(9725),
  "nyc-fc":       soccer(17844),
  "tor-fc":       soccer(6863),
  // Soccer
  "man-city":     soccer(382),
  "arsenal":      soccer(359),
  "chelsea":      soccer(363),
  "liverpool":    soccer(364),
  "man-utd":      soccer(360),
  "tottenham":    soccer(367),
  "barcelona":    soccer(83),
  "real-madrid":  soccer(86),
  "psg":          soccer(160),
  "juventus":     soccer(111),
  "dortmund":     soccer(124),
  "bayern":       soccer(132),
};
