import type { Request } from "express";

const bearer = [{ bearerAuth: [] }];
const errorResponses = {
  "400": { description: "Validation failed", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
  "401": { description: "Missing, expired, or invalid bearer token", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
  "403": { description: "Authenticated user does not have the required role", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
  "500": { description: "Unexpected server error", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
};

function protectedOperation(summary: string, description: string, role = "Fan") {
  return { summary, description: `${description} Required role: ${role}.`, tags: [role === "Fan" ? "Wallet & rewards" : "Administration"], security: bearer, responses: errorResponses };
}

const json = (schema: unknown) => ({ required: true, content: { "application/json": { schema } } });
const success = (description: string, schema: unknown) => ({ description, content: { "application/json": { schema } } });

/** The Swagger/OpenAPI document is intentionally maintained next to the HTTP
 * routes so deployed Swagger always describes the exact v1 mount point. */
export function openApiDocument(req: Request) {
  const configuredServer = process.env["OPENAPI_SERVER_URL"];
  const serverUrl = configuredServer || `${req.protocol}://${req.get("host")}/api/v1`;
  return {
    openapi: "3.1.0",
    info: { title: "RewLo API", version: "1.0.0", description: "Version 1 REST API for authenticated fan wallet, Brale settlement, and rewards operations." },
    servers: [{ url: serverUrl, description: configuredServer ? "Configured API server" : "Current request origin" }],
    tags: [
      { name: "Authentication", description: "Public session and account access operations." },
      { name: "Wallet & rewards", description: "Fan-only wallet, payment, card, offer, and transaction operations." },
      { name: "Administration", description: "Administrative enrollment reporting." },
      { name: "Merchant", description: "Merchant-scoped loyalty reporting and operational health." },
      { name: "System", description: "Health and operational integration endpoints." },
    ],
    paths: {
      "/healthz": { get: { tags: ["System"], summary: "Check API health", description: "Returns an unauthenticated liveness response for infrastructure monitoring.", responses: { "200": success("API is healthy", { $ref: "#/components/schemas/Health" }) } } },
      "/auth/register": { post: { tags: ["Authentication"], summary: "Create a fan account", description: "Creates a Fan account, provisions its Brale custody reference, and returns a JWT access/refresh token pair. Password must be at least 6 characters.", requestBody: json({ $ref: "#/components/schemas/RegisterRequest" }), responses: { "201": success("Account and session created", { $ref: "#/components/schemas/RegisterResponse" }), "400": errorResponses["400"], "409": { description: "Account already exists" }, "503": { description: "Brale wallet provisioning is temporarily unavailable" } } } },
      "/auth/login": { post: { tags: ["Authentication"], summary: "Authenticate a user and return JWT tokens", description: "Authenticates an active, provisioned Fan account using email and password.", requestBody: json({ $ref: "#/components/schemas/LoginRequest" }), responses: { "200": success("JWT token pair", { $ref: "#/components/schemas/TokenResponse" }), "401": errorResponses["401"] } } },
      "/auth/forgot-password": { post: { tags: ["Authentication"], summary: "Request password reset instructions", description: "Requests a single-use password-reset link. The response is intentionally identical for unknown emails.", requestBody: json({ $ref: "#/components/schemas/EmailRequest" }), responses: { "202": success("Request accepted", { $ref: "#/components/schemas/Message" }) } } },
      "/auth/reset-password": { post: { tags: ["Authentication"], summary: "Reset a password with a single-use token", description: "Sets a strong new password and revokes existing refresh sessions.", requestBody: json({ $ref: "#/components/schemas/ResetPasswordRequest" }), responses: { "204": { description: "Password reset successfully" }, "400": errorResponses["400"] } } },
      "/auth/refresh": { post: { tags: ["Authentication"], summary: "Rotate a refresh token", description: "Exchanges a valid refresh token for a new access/refresh token pair.", requestBody: json({ $ref: "#/components/schemas/RefreshRequest" }), responses: { "200": success("Rotated JWT token pair", { $ref: "#/components/schemas/TokenResponse" }), "401": errorResponses["401"] } } },
      "/auth/logout": { post: { ...protectedOperation("Revoke the current session", "Revokes the supplied refresh token and the bearer access token."), tags: ["Authentication"], requestBody: json({ $ref: "#/components/schemas/RefreshRequest" }), responses: { "204": { description: "Session revoked" }, "401": errorResponses["401"] } } },
      "/auth/account": { delete: { ...protectedOperation("Delete account", "Permanently deletes the authenticated account and its associated application data. Some provider or financial records may be retained where legally required."), tags: ["Authentication"], responses: { "200": success("Account deleted", { type: "object", properties: { deleted: { type: "boolean" } }, required: ["deleted"] }), "401": errorResponses["401"] } } },
      "/auth/me": { get: { ...protectedOperation("Get authenticated user profile", "Returns the safe profile and wallet-provisioning state for the bearer token."), tags: ["Authentication"], responses: { "200": success("Current user", { $ref: "#/components/schemas/CurrentUser" }), "401": errorResponses["401"] } } },
      "/merchant/overview": { get: { ...protectedOperation("Get merchant overview", "Returns only the authenticated merchant membership's aggregate loyalty, transfer, settlement, alert, and chart data. Raw ledger rows are never returned.", "Merchant"), tags: ["Merchant"], parameters: [{ name: "range", in: "query", schema: { type: "string", enum: ["7d", "30d", "90d", "custom"], default: "30d" } }, { name: "from", in: "query", schema: { type: "string", format: "date-time" } }, { name: "to", in: "query", schema: { type: "string", format: "date-time" } }], responses: { "200": success("Merchant overview", { $ref: "#/components/schemas/MerchantOverview" }), "400": errorResponses["400"], "401": errorResponses["401"], "403": { description: "Merchant role or active merchant membership is required" }, "500": errorResponses["500"] } } },
      "/wallet/summary": { get: { ...protectedOperation("Get authenticated user's wallet balance", "Returns current cash balance, reward points, and total completed wallet spend."), responses: { "200": success("Wallet summary", { $ref: "#/components/schemas/WalletSummary" }), ...errorResponses } } },
      "/wallet/transactions": { get: { ...protectedOperation("Get the user's wallet transaction history", "Returns a paginated, filterable unified ledger of wallet and reward activity."), parameters: [{ $ref: "#/components/parameters/Page" }, { $ref: "#/components/parameters/PageSize" }, { name: "type", in: "query", schema: { type: "string", enum: ["all", "send", "receive", "top_up", "reward_earned", "reward_redeemed", "merchant_payment", "mint", "burn"] } }, { name: "status", in: "query", schema: { type: "string", enum: ["all", "pending", "completed", "failed", "reversed"] } }, { name: "search", in: "query", schema: { type: "string", maxLength: 200 } }], responses: { "200": success("Paginated ledger", { $ref: "#/components/schemas/TransactionPage" }), ...errorResponses } } },
      "/wallet/transactions/refresh-pending": { post: { ...protectedOperation("Refresh pending Brale mint statuses", "Queries Brale for up to ten pending mints and updates completed, failed, or reversed ledger states."), responses: { "200": success("Refresh result", { $ref: "#/components/schemas/RefreshResult" }), ...errorResponses } } },
      "/wallet/cards": { get: { ...protectedOperation("List the user's payment cards", "Returns the authenticated user's verified payment instruments."), responses: { "200": success("Card list", { $ref: "#/components/schemas/CardList" }), ...errorResponses } } },
      "/wallet/cards/provision": { post: { ...protectedOperation("Provision Rewlo Premium card", "Creates the authenticated user's branded Rewlo Premium card when they do not already have one."), responses: { "201": success("Rewlo Premium card created", { $ref: "#/components/schemas/CardResponse" }), "200": success("Existing card", { $ref: "#/components/schemas/CardResponse" }), ...errorResponses } } },
      "/wallet/top-up": { post: { ...protectedOperation("Top up wallet", "Validates a verified payment card and creates the configured funding transaction before crediting RewLo cash."), requestBody: json({ $ref: "#/components/schemas/TopUpRequest" }), responses: { "201": success("Top-up completed", { $ref: "#/components/schemas/ReferenceResponse" }), "404": { description: "Card not found" }, "409": { description: "Brale wallet is not configured" }, "502": { description: "Brale provider error" }, ...errorResponses } } },
      "/wallet/users": { get: { ...protectedOperation("Search eligible wallet recipients", "Searches other fan accounts by name, email, or phone. Query must be at least two characters."), parameters: [{ name: "q", in: "query", required: true, schema: { type: "string", minLength: 2 } }], responses: { "200": success("Recipient search results", { $ref: "#/components/schemas/RecipientList" }), ...errorResponses } } },
      "/wallet/receive": { get: { ...protectedOperation("Get receive-money details", "Returns the authenticated fan's wallet identifier and QR deep-link value."), responses: { "200": success("Receive details", { $ref: "#/components/schemas/ReceiveDetails" }), "404": { description: "User not found" }, ...errorResponses } } },
      "/wallet/send": { post: { ...protectedOperation("Send wallet funds to another fan", "Transfers a positive USD amount to another fan through Brale and updates both wallet ledgers."), requestBody: json({ $ref: "#/components/schemas/SendRequest" }), responses: { "201": success("Transfer completed", { $ref: "#/components/schemas/ReferenceResponse" }), "409": { description: "Insufficient funds or wallet not configured" }, "502": { description: "Brale provider error" }, ...errorResponses } } },
      "/wallet/merchant-pay": { post: { ...protectedOperation("Pay a merchant from wallet balance", "Transfers wallet cash to a registered merchant using the merchant code and Brale custody addresses."), requestBody: json({ $ref: "#/components/schemas/MerchantPayRequest" }), responses: { "201": success("Merchant payment completed", { $ref: "#/components/schemas/ReferenceResponse" }), "409": { description: "Insufficient funds or wallet not configured" }, "404": { description: "Merchant not found" }, "502": { description: "Brale provider error" }, ...errorResponses } } },
      "/rewards": { get: { ...protectedOperation("Get available reward offers and reward totals", "Returns active database offers, redemption history, current points, and calculated reward statistics."), responses: { "200": success("Reward catalog", { $ref: "#/components/schemas/RewardsResponse" }), ...errorResponses } } },
      "/rewards/{offerId}/redeem": { post: { ...protectedOperation("Redeem an offer using RewLo points", "Redeems a real database offer through the Brale redemption workflow and deducts points atomically."), parameters: [{ name: "offerId", in: "path", required: true, schema: { type: "integer", minimum: 1 } }], responses: { "201": success("Offer redeemed", { $ref: "#/components/schemas/ReferenceResponse" }), "409": { description: "Insufficient points or offer already redeemed" }, "502": { description: "Brale provider error" }, ...errorResponses } } },
      "/merchants/{code}": { get: { ...protectedOperation("Look up a merchant by payment code", "Returns merchant details needed to confirm a wallet payment."), parameters: [{ name: "code", in: "path", required: true, schema: { type: "string", minLength: 1 }, description: "Case-insensitive merchant code" }], responses: { "200": success("Merchant", { $ref: "#/components/schemas/Merchant" }), "404": { description: "Merchant not found" }, ...errorResponses } } },
      "/send-welcome-email": { post: { tags: ["System"], summary: "Send a branded welcome email", description: "Sends a RewLo welcome message through the configured Resend connector. Authentication required; no additional role is currently enforced.", security: bearer, requestBody: json({ $ref: "#/components/schemas/WelcomeEmailRequest" }), responses: { "200": success("Email queued or sent", { $ref: "#/components/schemas/EmailResponse" }), "502": { description: "Email provider failure" }, ...errorResponses } } },
      "/register": { post: { tags: ["Authentication"], deprecated: true, summary: "Register legacy preview user", description: "Legacy v1 preview enrollment endpoint. New integrations must use /auth/register.", requestBody: json({ $ref: "#/components/schemas/LegacyRegisterRequest" }), responses: { "200": success("Preview registration completed", { $ref: "#/components/schemas/Message" }), "400": errorResponses["400"], "500": errorResponses["500"] } } },
      "/admin/stats": { get: { tags: ["Administration"], summary: "Get enrollment statistics", description: "Returns total enrollments and recent signups. Legacy endpoint: no authentication or role is currently enforced by the existing route; restrict it at the deployment boundary before production use.", responses: { "200": success("Enrollment statistics", { type: "object" }), "500": errorResponses["500"] } } },
    },
    components: {
      securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT", description: "Enter the JWT access token returned by /auth/login." } },
      parameters: { Page: { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } }, PageSize: { name: "pageSize", in: "query", schema: { type: "integer", minimum: 5, maximum: 50, default: 20 } } },
      schemas: {
        Error: { type: "object", required: ["error"], properties: { error: { type: "string", example: "Authentication is required" }, providerCode: { type: "string" }, providerRequestId: { type: "string" } } },
        Health: { type: "object", required: ["status"], properties: { status: { type: "string", example: "ok" } } },
        EmailRequest: { type: "object", required: ["email"], properties: { email: { type: "string", format: "email" } } },
        LoginRequest: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } },
        RegisterRequest: { type: "object", required: ["firstName", "lastName", "email", "password", "zipCode"], properties: { firstName: { type: "string", minLength: 1 }, lastName: { type: "string", minLength: 1 }, email: { type: "string", format: "email" }, password: { type: "string", minLength: 6 }, zipCode: { type: "string", minLength: 1 } } },
        ResetPasswordRequest: { type: "object", required: ["token", "newPassword"], properties: { token: { type: "string" }, newPassword: { type: "string", minLength: 12, format: "password" } } },
        RefreshRequest: { type: "object", required: ["refreshToken"], properties: { refreshToken: { type: "string" } } },
        TokenResponse: { type: "object", properties: { tokens: { $ref: "#/components/schemas/TokenPair" } } },
        TokenPair: { type: "object", properties: { accessToken: { type: "string" }, accessTokenExpiresIn: { type: "integer" }, refreshToken: { type: "string" }, refreshTokenExpiresAt: { type: "string", format: "date-time" } } },
        CurrentUser: { type: "object", properties: { id: { type: "integer" }, firstName: { type: "string" }, lastName: { type: "string" }, fullName: { type: "string" }, email: { type: "string", format: "email" }, role: { type: "string", example: "Fan" }, createdAt: { type: "string", format: "date-time" }, rewloPoints: { type: "integer" }, walletProvisioningStatus: { type: "string" } } },
        RegisterResponse: { type: "object", properties: { user: { type: "object" }, tokens: { $ref: "#/components/schemas/TokenPair" } } },
        WalletSummary: { type: "object", properties: { balanceCents: { type: "integer" }, rewardPoints: { type: "integer" }, totalSpendCents: { type: "integer" } } },
        TransactionPage: { type: "object", properties: { items: { type: "array", items: { $ref: "#/components/schemas/Transaction" } }, pagination: { type: "object" } } },
        Transaction: { type: "object", properties: { id: { type: "string" }, type: { type: "string" }, status: { type: "string" }, amountCents: { type: "integer" }, description: { type: "string" }, reference: { type: "string" }, createdAt: { type: "string", format: "date-time" } } },
        RefreshResult: { type: "object", properties: { checked: { type: "integer" }, updated: { type: "integer" }, unavailable: { type: "integer" } } },
        CardList: { type: "object", properties: { cards: { type: "array", items: { $ref: "#/components/schemas/Card" } } } }, CardResponse: { type: "object", properties: { card: { $ref: "#/components/schemas/Card" } } }, Card: { type: "object", properties: { id: { type: "integer" }, provider: { type: "string" }, last4Digits: { type: "string" }, expiry: { type: "string" } } },
        TopUpRequest: { type: "object", required: ["cardId", "amount"], properties: { cardId: { type: "integer" }, amount: { type: "string", pattern: "^\\d+(\\.\\d{1,2})?$", example: "10.00" } } },
        SendRequest: { type: "object", required: ["recipientId", "amount"], properties: { recipientId: { type: "integer", minimum: 1 }, amount: { type: "string", pattern: "^\\d+(\\.\\d{1,2})?$", example: "5.00" } } },
        MerchantPayRequest: { type: "object", required: ["merchantCode", "amount"], properties: { merchantCode: { type: "string" }, amount: { type: "string", pattern: "^\\d+(\\.\\d{1,2})?$" } } },
        ReferenceResponse: { type: "object", properties: { reference: { type: "string", format: "uuid" } } }, RecipientList: { type: "object", properties: { users: { type: "array", items: { type: "object" } } } }, ReceiveDetails: { type: "object", properties: { email: { type: "string" }, walletIdentifier: { type: "string" }, qrValue: { type: "string" } } },
        RewardsResponse: { type: "object", properties: { points: { type: "integer" }, stats: { type: "object" }, offers: { type: "array", items: { type: "object" } }, history: { type: "array", items: { type: "object" } } } }, Merchant: { type: "object", properties: { id: { type: "integer" }, code: { type: "string" }, name: { type: "string" }, description: { type: "string" } } },
        MerchantOverview: { type: "object", required: ["merchant", "range", "metrics", "transfers", "settlements", "alerts", "timeSeries"], properties: { merchant: { type: "object", properties: { code: { type: "string" }, name: { type: "string" } } }, range: { type: "object", properties: { key: { type: "string" }, from: { type: "string", format: "date-time" }, to: { type: "string", format: "date-time" } } }, metrics: { type: "object", properties: { rwloIssued: { type: "integer" }, rwloRedeemed: { type: "integer" }, rwloInCirculation: { type: "integer" }, netFloatCents: { type: "integer" }, netFloatLabel: { type: "string" }, netFloatBasis: { type: "string" } } }, transfers: { type: "object", properties: { inPoints: { type: "integer" }, outPoints: { type: "integer" }, pendingCount: { type: "integer" }, pendingPoints: { type: "integer" } } }, settlements: { type: "object" }, alerts: { type: "array", items: { type: "object" } }, timeSeries: { type: "array", items: { type: "object" } } } },
        WelcomeEmailRequest: { type: "object", required: ["email"], properties: { email: { type: "string", format: "email" }, name: { type: "string" }, teamName: { type: "string" }, gradientStart: { type: "string" }, gradientEnd: { type: "string" } } }, EmailResponse: { type: "object", properties: { success: { type: "boolean" }, emailId: { type: "string" } } }, Message: { type: "object", properties: { success: { type: "boolean" }, message: { type: "string" } } }, LegacyRegisterRequest: { type: "object", properties: { email: { type: "string", format: "email" }, password: { type: "string", minLength: 8 }, firstName: { type: "string" }, lastName: { type: "string" }, primaryClubId: { type: "string" }, followedClubIds: { type: "array", items: { type: "string" } }, zipCode: { type: "string" } } },
      },
    },
  };
}

export const swaggerUiHtml = `<!doctype html><html><head><meta charset="utf-8"><title>RewLo API Docs</title><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"></head><body><div id="swagger-ui"></div><script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script><script>SwaggerUIBundle({url:'/api-docs.json',dom_id:'#swagger-ui',persistAuthorization:true,displayRequestDuration:true});</script></body></html>`;
