import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import ClubBadge from "@/components/ClubBadge";
import { getClubById } from "@/constants/clubs";
import { useWallet } from "@/context/WalletContext";
import { useColors } from "@/hooks/useColors";
import { walletRequest } from "@/utils/walletApi";

type Recipient = { id: number; name: string; email: string; phoneNumber: string | null; primaryClubId: string };
type Phase = "search" | "amount" | "confirm" | "success";

export default function SendMoneyScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { balance, addTransaction } = useWallet();
  const [phase, setPhase] = useState<Phase>("search"); const [query, setQuery] = useState("");
  const [results, setResults] = useState<Recipient[]>([]); const [recipient, setRecipient] = useState<Recipient | null>(null);
  const [amount, setAmount] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [reference, setReference] = useState("");
  useEffect(() => { const timer = setTimeout(async () => { if (query.trim().length < 2) return setResults([]); try { const data = await walletRequest<{ users: Recipient[] }>(`/api/wallet/users?q=${encodeURIComponent(query)}`); setResults(data.users); } catch (e) { setError(e instanceof Error ? e.message : "Search failed"); } }, 300); return () => clearTimeout(timer); }, [query]);
  const dollars = Number(amount); const validAmount = dollars > 0 && Number.isFinite(dollars) && dollars <= balance;
  async function send() { if (!recipient || !validAmount || loading) return; setLoading(true); setError(""); try { const data = await walletRequest<{ reference: string }>("/api/wallet/send", { method: "POST", body: JSON.stringify({ recipientId: recipient.id, amount: dollars.toFixed(2) }) }); setReference(data.reference); addTransaction({ type: "send", amount: -dollars, description: `Sent to ${recipient.name}`, status: "completed" }); setPhase("success"); } catch (e) { setError(e instanceof Error ? e.message : "Transfer failed"); } finally { setLoading(false); } }
  return <View style={[s.root, { backgroundColor: colors.background, paddingTop: insets.top }]}>
    <View style={s.header}><Pressable onPress={() => phase === "search" ? router.back() : setPhase(phase === "confirm" ? "amount" : "search")}><Ionicons name="arrow-back" size={24} color={colors.foreground}/></Pressable><Text style={[s.title,{color:colors.foreground}]}>Send Money</Text><View style={{width:24}}/></View>
    <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
      {phase === "search" && <><Text style={[s.heading,{color:colors.foreground}]}>Who are you sending to?</Text><View style={[s.search,{backgroundColor:colors.card,borderColor:colors.border}]}><Ionicons name="search" size={20} color={colors.mutedForeground}/><TextInput value={query} onChangeText={setQuery} placeholder="Search name, email or phone" placeholderTextColor={colors.mutedForeground} style={[s.input,{color:colors.foreground}]}/></View>{results.map(u=><Pressable key={u.id} onPress={()=>{setRecipient(u);setPhase("amount")}} style={[s.person,{borderColor:colors.border,backgroundColor:colors.card}]}><ClubBadge club={getClubById(u.primaryClubId)} size={48}/><View style={{flex:1}}><Text style={[s.personName,{color:colors.foreground}]}>{u.name}</Text><Text style={[s.meta,{color:colors.mutedForeground}]}>{u.email}</Text>{u.phoneNumber&&<Text style={[s.meta,{color:colors.mutedForeground}]}>{u.phoneNumber}</Text>}</View><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground}/></Pressable>)}</>}
      {phase === "amount" && recipient && <><RecipientCard user={recipient}/><Text style={[s.label,{color:colors.mutedForeground}]}>AMOUNT</Text><View style={s.amountRow}><Text style={[s.dollar,{color:colors.foreground}]}>$</Text><TextInput value={amount} onChangeText={v=>setAmount(v.replace(/[^0-9.]/g,""))} autoFocus keyboardType="decimal-pad" placeholder="0.00" placeholderTextColor={colors.mutedForeground} style={[s.amount,{color:colors.foreground}]}/></View><Text style={[s.balance,{color:colors.mutedForeground}]}>Available ${balance.toFixed(2)}</Text><Primary disabled={!validAmount} label="Continue" onPress={()=>setPhase("confirm")}/></>}
      {phase === "confirm" && recipient && <><Text style={[s.heading,{color:colors.foreground}]}>Confirm transfer</Text><RecipientCard user={recipient}/><View style={[s.summary,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[s.meta,{color:colors.mutedForeground}]}>You send</Text><Text style={[s.total,{color:colors.foreground}]}>${dollars.toFixed(2)}</Text><Text style={[s.meta,{color:colors.mutedForeground}]}>Solana Devnet · RewLo Cash</Text></View><Primary disabled={loading} label={loading?"Sending…":`Send $${dollars.toFixed(2)}`} onPress={send}/></>}
      {phase === "success" && recipient && <View style={s.success}><Ionicons name="checkmark-circle" size={92} color={colors.success}/><Text style={[s.heading,{color:colors.foreground}]}>Money sent!</Text><Text style={[s.meta,{color:colors.mutedForeground}]}>${dollars.toFixed(2)} was sent to {recipient.name}</Text><View style={[s.summary,{backgroundColor:colors.card,borderColor:colors.border,width:"100%"}]}><Text style={[s.meta,{color:colors.mutedForeground}]}>Transaction reference</Text><Text selectable style={[s.ref,{color:colors.foreground}]}>{reference}</Text></View><Primary label="Done" onPress={()=>router.back()}/></View>}
      {!!error&&<Text style={s.error}>{error}</Text>}
    </ScrollView></View>;
}
function RecipientCard({user}:{user:Recipient}) { const colors=useColors(); return <View style={[s.selected,{backgroundColor:colors.card,borderColor:colors.border}]}><ClubBadge club={getClubById(user.primaryClubId)} size={54}/><View><Text style={[s.personName,{color:colors.foreground}]}>{user.name}</Text><Text style={[s.meta,{color:colors.mutedForeground}]}>{user.email}</Text></View></View> }
function Primary({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}) { return <Pressable disabled={disabled} onPress={onPress} style={{opacity:disabled ? 0.45 : 1,marginTop:24}}><LinearGradient colors={["#00E5CC","#2563EB"]} style={s.primary}><Text style={s.primaryText}>{label}</Text></LinearGradient></Pressable> }
const s=StyleSheet.create({root:{flex:1},header:{height:60,paddingHorizontal:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontSize:18,fontFamily:"Inter_700Bold"},content:{padding:20,paddingBottom:50},heading:{fontSize:23,fontFamily:"Inter_700Bold",marginBottom:18},search:{height:54,borderRadius:16,borderWidth:1,paddingHorizontal:15,flexDirection:"row",alignItems:"center",gap:10,marginBottom:16},input:{flex:1,fontSize:15},person:{flexDirection:"row",alignItems:"center",gap:13,padding:14,borderRadius:16,borderWidth:1,marginBottom:10},personName:{fontSize:15,fontFamily:"Inter_600SemiBold"},meta:{fontSize:13,fontFamily:"Inter_400Regular",marginTop:3},selected:{flexDirection:"row",alignItems:"center",gap:14,padding:16,borderRadius:18,borderWidth:1,marginBottom:30},label:{fontSize:12,fontFamily:"Inter_600SemiBold",letterSpacing:1,textAlign:"center"},amountRow:{flexDirection:"row",justifyContent:"center",alignItems:"center",marginTop:10},dollar:{fontSize:40,fontFamily:"Inter_500Medium"},amount:{fontSize:58,fontFamily:"Inter_700Bold",minWidth:150},balance:{textAlign:"center",fontSize:14},primary:{height:56,borderRadius:16,alignItems:"center",justifyContent:"center"},primaryText:{color:"white",fontSize:16,fontFamily:"Inter_700Bold"},summary:{padding:20,borderRadius:18,borderWidth:1,alignItems:"center",gap:7},total:{fontSize:38,fontFamily:"Inter_700Bold"},success:{alignItems:"center",paddingTop:30,gap:8},ref:{fontSize:13,fontFamily:"Inter_600SemiBold",textAlign:"center",marginTop:6},error:{color:"#EF4444",fontSize:13,textAlign:"center",marginTop:16}});
